import React, { FC } from 'react'
import Head from 'next/head'
import { ArticleContainer } from 'components/Article/Article'
import { GetServerSideProps } from 'types/next'

export const getServerSideProps: GetServerSideProps = async ({ params }) => {
   return {
      props: params,
   }
}

export type ArticleType = {
   id: string
}

export const Article: FC<ArticleType> = (props) => {
   return (
      <div>
         <Head>
            <title>Article</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <ArticleContainer id={props.id} />
      </div>
   )
}

export default Article
