on:
   # [push]
   # Remove next block to enable
   push:
      branches-ignore:
         - '**'
name: CI/CD
env:
   SENTRY_ORG: ''
   SENTRY_PROJECT: ''
jobs:
   sentry:
      name: Create Sentry Release
      needs: test
      runs-on: ubuntu-20.04
      steps:
         - name: Checkout 🛎
           uses: actions/checkout@v2
           with:
              fetch-depth: 0
         - name: Create Sentry release
           uses: getsentry/action-release@v1
           env:
              SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
              SENTRY_ORG: ${{ env.SENTRY_ORG }}
              SENTRY_PROJECT: ${{ env.SENTRY_PROJECT }}
           with:
              environment: production
